pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["overview.htm","Forgot Password","Forgot Password Top Previous Next If you forget your password, click on &#39;Lost Password&#39; as shown in the image below to reset your password. When c...",""],
["chapter_2.htm","Login","Login Top Previous Next Enter the URL in the address bar and press enter button. This will take you to the login page. Enter your registered usern...",""],
["my_profile.htm","My Profile","My Profile Top Previous Next View Profile View Profile page allows the user to view his/her profile. The profile shows their image, description, c...",""],
["my_students.htm","My Students","My Students Top Previous Next My students page shows the list of students assigned to a mentor. The user, here can view the students&#39; profile (cli...",""],
["introduction.htm","Introduction","Introduction Top Next This document outlines the user manual of College/Student Information Management System and to create a help manual for the ...",""],
["add_drop_courses.htm","Add/Drop Courses","Add/Drop Courses Top Previous Add/Drop Course Add/Drop page facilitates the student to add or drop a course. 1.Add Course button - to request a ne...",""],
["enrolled_courses.htm","Enrolled Courses","Enrolled Courses Top Previous Next Approve Enrolled Courses will have tabs for pending approvals and completed approvals. You are here: My Tasks C...",""],
["general_settings.htm","General Settings","General Settings Top Previous Next These settings are common for all the users in Cobalt Learning Management System. Login My Profile ",""],
["course_registration2.htm","Course Registration","Course Registration Top Previous Next Enrolled Courses Add/Drop Courses ",""],
["academic_advisor_v1_ftsearch.htm","CobaltLMS","Contents | Index | Search Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): You must have JavaScript enabled to use this...",""],
["getting_started_-_academic_adv.htm","Getting Started - Academic Advisor","Getting Started - Academic Advisor Top Previous Next My Students Course Registration My Profile ",""]];
