pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["overview.htm","Forgot Password","Forgot Password Top Previous Next If you forget your password, click on &#39;Lost Password&#39; as shown in the image below to reset your password. When c...",""],
["chapter_2.htm","Login","Login Top Previous Next Enter the URL in the address bar and press enter button. This will take you to the login page. Enter your registered usern...",""],
["my_clclasses.htm","My Classes","My Classes Top Previous Next Current Classes The information of the on-going semester clclasses will be displayed, when clicked on current clclasses. ...",""],
["my_profile.htm","My Profile","My Profile Top Previous Next View Profile View Profile page allows the user to view his/her profile. The profile shows their image, description, c...",""],
["evaluations2.htm","Evaluations","Evaluations Top Previous Instructor can view the evaluations here. The user can apply filters to manage the view of evaluations and can navigate b...",""],
["introduction.htm","Introduction","Introduction Top Next This document outlines the user manual of College/Student Information Management System and to create a help manual for the ...",""],
["general_settings.htm","General Settings","General Settings Top Previous Next These settings are common for all the users in Cobalt Learning Management System. Login My Profile ",""],
["academic_calendar2.htm","Academic Calendar","Academic Calendar Top Previous Next The Instructor has access to the following: 1.Change academic calendar view (week, month, year) 2.Apply filter...",""],
["instructor_v1_ftsearch.htm","CobaltLMS","Contents | Index | Search Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): You must have JavaScript enabled to use this...",""],
["getting_started_-_instructor.htm","Getting Started - Instructor","Getting Started - Instructor Top Previous Next Academic Calendar My Classes Evaluations My Profile ",""]];
