pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["id_card.htm","ID Card","ID Card Top Previous Next 1.View Displays list of Id card requests with the status. The user can manage the view by applying filters and also can ...",""],
["overview.htm","Forgot Password","Forgot Password Top Previous Next If you forget your password, click on &#39;Lost Password&#39; as shown in the image below to reset your password. When c...",""],
["chapter_2.htm","Login","Login Top Previous Next Enter the URL in the address bar and press enter button. This will take you to the login page. Enter your registered usern...",""],
["my_profile.htm","My Profile","My Profile Top Previous Next View Profile View Profile page allows the user to view his/her profile. The profile shows their image, description, c...",""],
["transcript.htm","Transcript","Transcript Top Previous Next 1.View View page allows the student to download the semester wise transcripts, that are approved. The user can manage...",""],
["my_requests.htm","My Requests","My Requests Top Previous Next ID Card - Request for an Id card Profile Change - Request for profile change Transcript - Request for transcript Cou...",""],
["introduction.htm","Introduction","Introduction Top Next This document outlines the user manual of College/Student Information Management System and to create a help manual for the ...",""],
["my_academics.htm","My Academics","My Academics Top Previous Next My Academics has the following tabs: My Plan My Plan page shows the curriculum information based on the program, th...",""],
["profile_change.htm","Profile Change","Profile Change Top Previous Next 1.View View page shows the list of profile change requests made. The user can manage the view by applying filters...",""],
["add_drop_course.htm","Add/Drop Course","Add/Drop Course Top Previous Next Add/Drop Course Add/Drop page facilitates the student to add or drop a course. 1.Add Course button - to request ...",""],
["course_exemption.htm","Course Exemption","Course Exemption Top Previous 1.View Displays list of course exemption requests. View Screenshot 2.New Request This page allows the student to mak...",""],
["general_settings.htm","General Settings","General Settings Top Previous Next These settings are common for all the users in Cobalt Learning Management System. Login My Profile ",""],
["student_v1_ftsearch.htm","CobaltLMS","Contents | Index | Search Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): You must have JavaScript enabled to use this...",""],
["course_registration3.htm","Course Registration","Course Registration Top Previous Next Register to a course Add/Drop Course ",""],
["register_to_a_course.htm","Register to a course","Register to a course Top Previous Next Register to a course has the following 2 tabs: Course Registration Course Registration page shows the list ...",""],
["getting_started_-_student.htm","Getting Started - Student","Getting Started - Student Top Previous Next My Academics Course Registration My Requests My Profile ",""]];
