pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["grades.htm","Grades","Grades Top Previous Next To evaluate student&#39;s performance. Grades has the following submenu. Grade Letters Exam Type Lecture Type Grade Submission ",""],
["courses.htm","Courses","Courses Top Previous Next Cobalt courses are the units of learning which are created for departments under a school. Courses are assigned to progr...",""],
["id_card.htm","ID Card","ID Card Top Previous Next 1.View Displays list of Id card requests with the status. The user can manage the view by applying filters and also can ...",""],
["modules.htm","Modules","Modules Top Previous Next Modules is a set of courses assigned to a curriculum. You are here: University Structure Modules Click on &#39;Modules&#39; as s...",""],
["schools.htm","Schools","Schools Top Previous Next A School is defined as an institute that offers programs. CobaltLMS offers to manage multiple schools. You are here: Uni...",""],
["overview.htm","Forgot Password","Forgot Password Top Previous Next If you forget your password, click on &#39;Lost Password&#39; as shown in the image below to reset your password. When c...",""],
["programs.htm","Programs","Programs Top Previous Next Program is an academic qualification. Schools offer various graduate and under-graduate programs. You are here: Univers...",""],
["chapter_2.htm","Login","Login Top Previous Next Enter the URL in the address bar and press enter button. This will take you to the login page. Enter your registered usern...",""],
["exam_type.htm","Exam Type","Exam Type Top Previous Next To define exam types, the registrar has to click on &#39;Exam Type menu&#39;. You are here: University Structure Grades Exam T...",""],
["semesters.htm","Semesters","Semesters Top Previous Next The academic year of each program is divided into semesters. Each academic year may have 2 or 3 semester. You are here...",""],
["admissions.htm","Admissions","Admissions Top Previous Next Registrars approve/reject an applicant as part of admission process. You are here: University Structure Admissions Re...",""],
["graduation.htm","Graduation","Graduation Top Previous Next The students who satisfy all the academic conditions will be awarded degree. Under Graduation, the registrar has acce...",""],
["my_clclasses.htm","My Classes","My Classes Top Previous Next Current Classes The information of the on-going semester clclasses will be displayed, when clicked on current clclasses. ...",""],
["my_profile.htm","My Profile","My Profile Top Previous Next View Profile View Profile page allows the user to view his/her profile. The profile shows their image, description, c...",""],
["transcript.htm","Transcript","Transcript Top Previous Next 1.View View page allows the student to download the semester wise transcripts, that are approved. The user can manage...",""],
["curriculums.htm","Curriculums","Curriculums Top Previous Next Each program has a different curriculum which includes a set of courses. You are here: University Structure Curricul...",""],
["departments.htm","Departments","Departments Top Previous Next Schools have various departments. The registrar can assign a department to multiple schools. You are here: Universit...",""],
["evaluations.htm","Evaluations","Evaluations Top Previous Next Registrar can determine the criteria to evaluate students and instructors through evaluations. You are here: Univers...",""],
["manage_plan.htm","Manage Plan","Manage Plan Top Previous Next Enter topic text here. ",""],
["my_requests.htm","My Requests","My Requests Top Previous Next ID Card - Request for an Id card Profile Change - Request for profile change Transcript - Request for transcript Cou...",""],
["my_students.htm","My Students","My Students Top Previous Next My students page shows the list of students assigned to a mentor. The user, here can view the students&#39; profile (cli...",""],
["evaluations2.htm","Evaluations","Evaluations Top Previous Next Instructor can view the evaluations here. The user can apply filters to manage the view of evaluations and can navig...",""],
["examinations.htm","Examinations","Examinations Top Previous Next Examinations can be created here. Through examinations the students will evaluated. You are here: University Struct...",""],
["introduction.htm","Introduction","Introduction Top Next This document outlines the user manual of College/Student Information Management System and to create a help manual for the ...",""],
["lecture_type.htm","Lecture Type","Lecture Type Top Previous Next To access lecture type page, the registrar has to click on &#39;Lecture Type menu&#39;. You are here: University Structure ...",""],
["my_academics.htm","My Academics","My Academics Top Previous Next My Academics has the following tabs: My Plan My Plan page shows the curriculum information based on the program, th...",""],
["grade_letters.htm","Grade Letters","Grade Letters Top Previous Next The registrar can define grade letters for grade points here. Under Grade Letters, the registrar has access to the...",""],
["manage_floors.htm","Manage Floors","Manage Floors Top Previous Next You are here: University Structure Resource Management - Manage Floors View Floors To access &#39;View Floors&#39; page cl...",""],
["profile_change.htm","Profile Change","Profile Change Top Previous Next 1.View View page shows the list of profile change requests made. The user can manage the view by applying filters...",""],
["add_drop_course.htm","Add/Drop Course","Add/Drop Course Top Previous Next Add/Drop Course Add/Drop page facilitates the student to add or drop a course. 1.Add Course button - to request ...",""],
["getting_started.htm","Getting Started","Getting Started Top Previous Next Getting stated in CobaltLMS is very simply. The registered users will have a specific role. Select any of the fo...",""],
["add_drop_courses.htm","Add/Drop Courses","Add/Drop Courses Top Previous Next Enter topic text here. ",""],
["course_exemption.htm","Course Exemption","Course Exemption Top Previous 1.View Displays list of course exemption requests. View Screenshot 2.New Request This page allows the student to mak...",""],
["enrolled_courses.htm","Enrolled Courses","Enrolled Courses Top Previous Next Approve Enrolled Courses will have tabs for pending approvals and completed approvals. You are here: My Tasks C...",""],
["general_settings.htm","General Settings","General Settings Top Previous Next These settings are common for all the users in Cobalt Learning Management System. Login My Profile ",""],
["grade_submission.htm","Grade Submission","Grade Submission Top Previous Next Grade Submission page allows the registrar to submit grades to individual students based on their performance i...",""],
["manage_buildings.htm","Manage Buildings","Manage Buildings Top Previous Next You are here: University Structure Resource Management - Manage Buildings View Buildings When clicked on &#39;Manag...",""],
["manage_resources.htm","Manage Resources","Manage Resources Top Previous Next You are here: University Structure Resource Management - Manage Resources View Resources On clicking &#39;Manage Re...",""],
["academic_calendar.htm","Academic Calendar","Academic Calendar Top Previous Next Academic Calendar is the annual publication by the colleges and has the list of events. You are here: Universi...",""],
["manage_classrooms.htm","Manage Classrooms","Manage Classrooms Top Previous Next You are here: University Structure Resource Management - Manage Classrooms View Classrooms When clicked on &#39;Ma...",""],
["academic_calendar2.htm","Academic Calendar","Academic Calendar Top Previous Next The Instructor has access to the following: 1.Change academic calendar view (week, month, year) 2.Apply filter...",""],
["clclasses_management.htm","Classes Management","Classes Management Top Previous Next Classes are created for courses. Classes are scheduled based on the course requirement, number of students, i...",""],
["course_registration.htm","Course Registration","Course Registration Top Previous Next Course Registration allows the registrar to approve/reject the requests, for enrolled courses and add/drop c...",""],
["resource_management.htm","Resource Management","Resource Management Top Previous Next Schools have resources such as buildings, floors, classrooms, classroom resources. &#39;Resource Management&#39; all...",""],
["course_registration2.htm","Course Registration","Course Registration Top Previous Next Enrolled Courses Add/Drop Courses ",""],
["course_registration3.htm","Course Registration","Course Registration Top Previous Next Register to a course Add/Drop Course ",""],
["register_to_a_course.htm","Register to a course","Register to a course Top Previous Next Register to a course has the following 2 tabs: Course Registration Course Registration page shows the list ...",""],
["registrar_v1_ftsearch.htm","CobaltLMS","Contents | Index | Search Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): You must have JavaScript enabled to use this...",""],
["manage_academic_advisor.htm","Manage Academic Advisor","Manage Academic Advisor Top Previous Manage Academic Advisor is a feature where in the registrar can assign an Advisor/Mentor to a student. View T...",""],
["approve_add_drop_courses.htm","Approve Add/Drop Courses","Approve Add/Drop Courses Top Previous Next Approve Add/Drop courses will have tabs for pending approvals list and completed approvals list. You ar...",""],
["approve_enrolled_courses.htm","Approve Enrolled Courses","Approve Enrolled Courses Top Previous Next Approve Enrolled Courses will have tabs for pending approvals and completed approvals. You are here: Un...",""],
["getting_started_-_student.htm","Getting Started - Student","Getting Started - Student Top Previous Next My Academics Course Registration My Requests My Profile ",""],
["getting_started_-_registrar.htm","Getting Started - Registrar","Getting Started - Registrar Top Previous Next The Getting Started - Registrar guide will help you to know the Registrar&#39;s activities and the Cobal...",""],
["getting_started_-_instructor.htm","Getting Started - Instructor","Getting Started - Instructor Top Previous Next Academic Calendar My Classes Evaluations My Profile ",""],
["getting_started_-_academic_adv.htm","Getting Started - Academic Advisor","Getting Started - Academic Advisor Top Previous Next My Students Course Registration My Profile ",""]];
